# Generated by Django 5.2.6 on 2025-09-24 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_area', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad_maxima', models.IntegerField()),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('costo_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('requiere_reserva', models.BooleanField(default=True)),
                ('tiempo_max_reserva', models.IntegerField(default=2)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'areas_comunes',
                'managed': False,
            },
        ),
    ]
