# Generated by Django 5.2.4 on 2025-09-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='residente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
