# Generated by Django 5.2.6 on 2025-09-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_personal_options_alter_propietario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personal',
            table='personal',
        ),
        migrations.AlterModelTable(
            name='propietario',
            table='propietario',
        ),
        migrations.AlterModelTable(
            name='residente',
            table='residente',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
